//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.09 at 09:39:03 AM IST 
//


package com.springboot.soap.webservices.db.crud.dto;

import javax.xml.namespace.QName;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.springboot.soap.webservices.db.crud.dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetEmployeeRequest_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "getEmployeeRequest");
    private final static QName _GetEmployeeResponse_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "getEmployeeResponse");
    private final static QName _GetCompanyResponse_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "getCompanyResponse");
    private final static QName _CreateCompanyRequest_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "createCompanyRequest");
    private final static QName _GetCompanyRequest_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "getCompanyRequest");
    private final static QName _UpdateCompanyRequest_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "updateCompanyRequest");
    private final static QName _CreateEmployeeResponse_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "createEmployeeResponse");
    private final static QName _UpdateCompanyResponse_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "updateCompanyResponse");
    private final static QName _UpdateEmployeeResponse_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "updateEmployeeResponse");
    private final static QName _UpdateEmployeeRequest_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "updateEmployeeRequest");
    private final static QName _DeleteEmployeeResponse_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "deleteEmployeeResponse");
    private final static QName _CreateEmployeeRequest_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "createEmployeeRequest");
    private final static QName _CreateCompanyResponse_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "createCompanyResponse");
    private final static QName _DeleteCompanyResponse_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "deleteCompanyResponse");
    private final static QName _DeleteEmployeeRequest_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "deleteEmployeeRequest");
    private final static QName _DeleteCompanyRequest_QNAME = new QName("http://crud.db.webservices.soap.springboot.com/dto", "deleteCompanyRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.springboot.soap.webservices.db.crud.dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCompanyResponse }
     * 
     */
    public GetCompanyResponse createGetCompanyResponse() {
        return new GetCompanyResponse();
    }

    /**
     * Create an instance of {@link CreateCompanyRequest }
     * 
     */
    public CreateCompanyRequest createCreateCompanyRequest() {
        return new CreateCompanyRequest();
    }

    /**
     * Create an instance of {@link GetCompanyRequest }
     * 
     */
    public GetCompanyRequest createGetCompanyRequest() {
        return new GetCompanyRequest();
    }

    /**
     * Create an instance of {@link GetEmployeeRequest }
     * 
     */
    public GetEmployeeRequest createGetEmployeeRequest() {
        return new GetEmployeeRequest();
    }

    /**
     * Create an instance of {@link GetEmployeeResponse }
     * 
     */
    public GetEmployeeResponse createGetEmployeeResponse() {
        return new GetEmployeeResponse();
    }

    /**
     * Create an instance of {@link DeleteEmployeeResponse }
     * 
     */
    public DeleteEmployeeResponse createDeleteEmployeeResponse() {
        return new DeleteEmployeeResponse();
    }

    /**
     * Create an instance of {@link CreateEmployeeRequest }
     * 
     */
    public CreateEmployeeRequest createCreateEmployeeRequest() {
        return new CreateEmployeeRequest();
    }

    /**
     * Create an instance of {@link CreateCompanyResponse }
     * 
     */
    public CreateCompanyResponse createCreateCompanyResponse() {
        return new CreateCompanyResponse();
    }

    /**
     * Create an instance of {@link DeleteCompanyResponse }
     * 
     */
    public DeleteCompanyResponse createDeleteCompanyResponse() {
        return new DeleteCompanyResponse();
    }

    /**
     * Create an instance of {@link DeleteEmployeeRequest }
     * 
     */
    public DeleteEmployeeRequest createDeleteEmployeeRequest() {
        return new DeleteEmployeeRequest();
    }

    /**
     * Create an instance of {@link DeleteCompanyRequest }
     * 
     */
    public DeleteCompanyRequest createDeleteCompanyRequest() {
        return new DeleteCompanyRequest();
    }

    /**
     * Create an instance of {@link UpdateCompanyRequest }
     * 
     */
    public UpdateCompanyRequest createUpdateCompanyRequest() {
        return new UpdateCompanyRequest();
    }

    /**
     * Create an instance of {@link CreateEmployeeResponse }
     * 
     */
    public CreateEmployeeResponse createCreateEmployeeResponse() {
        return new CreateEmployeeResponse();
    }

    /**
     * Create an instance of {@link UpdateCompanyResponse }
     * 
     */
    public UpdateCompanyResponse createUpdateCompanyResponse() {
        return new UpdateCompanyResponse();
    }

    /**
     * Create an instance of {@link UpdateEmployeeResponse }
     * 
     */
    public UpdateEmployeeResponse createUpdateEmployeeResponse() {
        return new UpdateEmployeeResponse();
    }

    /**
     * Create an instance of {@link UpdateEmployeeRequest }
     * 
     */
    public UpdateEmployeeRequest createUpdateEmployeeRequest() {
        return new UpdateEmployeeRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "getEmployeeRequest")
    public JAXBElement<GetEmployeeRequest> createGetEmployeeRequest(GetEmployeeRequest value) {
        return new JAXBElement<GetEmployeeRequest>(_GetEmployeeRequest_QNAME, GetEmployeeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEmployeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "getEmployeeResponse")
    public JAXBElement<GetEmployeeResponse> createGetEmployeeResponse(GetEmployeeResponse value) {
        return new JAXBElement<GetEmployeeResponse>(_GetEmployeeResponse_QNAME, GetEmployeeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCompanyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "getCompanyResponse")
    public JAXBElement<GetCompanyResponse> createGetCompanyResponse(GetCompanyResponse value) {
        return new JAXBElement<GetCompanyResponse>(_GetCompanyResponse_QNAME, GetCompanyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCompanyRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "createCompanyRequest")
    public JAXBElement<CreateCompanyRequest> createCreateCompanyRequest(CreateCompanyRequest value) {
        return new JAXBElement<CreateCompanyRequest>(_CreateCompanyRequest_QNAME, CreateCompanyRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCompanyRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "getCompanyRequest")
    public JAXBElement<GetCompanyRequest> createGetCompanyRequest(GetCompanyRequest value) {
        return new JAXBElement<GetCompanyRequest>(_GetCompanyRequest_QNAME, GetCompanyRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCompanyRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "updateCompanyRequest")
    public JAXBElement<UpdateCompanyRequest> createUpdateCompanyRequest(UpdateCompanyRequest value) {
        return new JAXBElement<UpdateCompanyRequest>(_UpdateCompanyRequest_QNAME, UpdateCompanyRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateEmployeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "createEmployeeResponse")
    public JAXBElement<CreateEmployeeResponse> createCreateEmployeeResponse(CreateEmployeeResponse value) {
        return new JAXBElement<CreateEmployeeResponse>(_CreateEmployeeResponse_QNAME, CreateEmployeeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateCompanyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "updateCompanyResponse")
    public JAXBElement<UpdateCompanyResponse> createUpdateCompanyResponse(UpdateCompanyResponse value) {
        return new JAXBElement<UpdateCompanyResponse>(_UpdateCompanyResponse_QNAME, UpdateCompanyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEmployeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "updateEmployeeResponse")
    public JAXBElement<UpdateEmployeeResponse> createUpdateEmployeeResponse(UpdateEmployeeResponse value) {
        return new JAXBElement<UpdateEmployeeResponse>(_UpdateEmployeeResponse_QNAME, UpdateEmployeeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateEmployeeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "updateEmployeeRequest")
    public JAXBElement<UpdateEmployeeRequest> createUpdateEmployeeRequest(UpdateEmployeeRequest value) {
        return new JAXBElement<UpdateEmployeeRequest>(_UpdateEmployeeRequest_QNAME, UpdateEmployeeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteEmployeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "deleteEmployeeResponse")
    public JAXBElement<DeleteEmployeeResponse> createDeleteEmployeeResponse(DeleteEmployeeResponse value) {
        return new JAXBElement<DeleteEmployeeResponse>(_DeleteEmployeeResponse_QNAME, DeleteEmployeeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateEmployeeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "createEmployeeRequest")
    public JAXBElement<CreateEmployeeRequest> createCreateEmployeeRequest(CreateEmployeeRequest value) {
        return new JAXBElement<CreateEmployeeRequest>(_CreateEmployeeRequest_QNAME, CreateEmployeeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCompanyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "createCompanyResponse")
    public JAXBElement<CreateCompanyResponse> createCreateCompanyResponse(CreateCompanyResponse value) {
        return new JAXBElement<CreateCompanyResponse>(_CreateCompanyResponse_QNAME, CreateCompanyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteCompanyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "deleteCompanyResponse")
    public JAXBElement<DeleteCompanyResponse> createDeleteCompanyResponse(DeleteCompanyResponse value) {
        return new JAXBElement<DeleteCompanyResponse>(_DeleteCompanyResponse_QNAME, DeleteCompanyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteEmployeeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "deleteEmployeeRequest")
    public JAXBElement<DeleteEmployeeRequest> createDeleteEmployeeRequest(DeleteEmployeeRequest value) {
        return new JAXBElement<DeleteEmployeeRequest>(_DeleteEmployeeRequest_QNAME, DeleteEmployeeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteCompanyRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://crud.db.webservices.soap.springboot.com/dto", name = "deleteCompanyRequest")
    public JAXBElement<DeleteCompanyRequest> createDeleteCompanyRequest(DeleteCompanyRequest value) {
        return new JAXBElement<DeleteCompanyRequest>(_DeleteCompanyRequest_QNAME, DeleteCompanyRequest.class, null, value);
    }

}
