//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.09 at 09:39:03 AM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://crud.db.webservices.soap.springboot.com/dto", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.springboot.soap.webservices.db.crud.dto;
