//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.09 at 09:39:03 AM IST 
//


package com.springboot.soap.webservices.db.crud.entity;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.Id;


/**
 * <p>Java class for employee complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="employee">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="employeeId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="employeeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employeeDepartment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employeeEmailAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="employeeContactNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "employee", propOrder = {
    "employeeId",
    "employeeName",
    "employeeDepartment",
    "employeeEmailAddress",
    "employeeContactNumber"
})
@Entity
@Table(name = "Employee")
public class Employee 
{
	@Id
	@Column(name = "employeeId")
	protected long employeeId;
    @XmlElement(required = true)
    @Column(name = "employeeName")
    protected String employeeName;
    @XmlElement(required = true)
    @Column(name = "employeeDepartment")
    protected String employeeDepartment;
    @XmlElement(required = true)
    @Column(name = "employeeEmailAddress")
    protected String employeeEmailAddress;
    @XmlElement(required = true)
    @Column(name = "employeeContactNumber")
    protected String employeeContactNumber;

    /**
     * Gets the value of the employeeId property.
     * 
     */
    public long getEmployeeId() {
        return employeeId;
    }

    /**
     * Sets the value of the employeeId property.
     * 
     */
    public void setEmployeeId(long value) {
        this.employeeId = value;
    }

    /**
     * Gets the value of the employeeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * Sets the value of the employeeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeName(String value) {
        this.employeeName = value;
    }

    /**
     * Gets the value of the employeeDepartment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeDepartment() {
        return employeeDepartment;
    }

    /**
     * Sets the value of the employeeDepartment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeDepartment(String value) {
        this.employeeDepartment = value;
    }

    /**
     * Gets the value of the employeeEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeEmailAddress() {
        return employeeEmailAddress;
    }

    /**
     * Sets the value of the employeeEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeEmailAddress(String value) {
        this.employeeEmailAddress = value;
    }

    /**
     * Gets the value of the employeeContactNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeContactNumber() {
        return employeeContactNumber;
    }

    /**
     * Sets the value of the employeeContactNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeContactNumber(String value) {
        this.employeeContactNumber = value;
    }

}
